FROM quay.io/quarkus/ubi-quarkus-native-image:22.2-java17 as build

USER root
WORKDIR /build
RUN mkdir -p .mvn/wrapper

COPY . .

RUN ./mvnw package -Pnative

################################

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --from=build build/target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

