kind: Deployment
apiVersion: apps/v1
metadata:
  name: quote-consumer
  labels:
    app: quote-consumer
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-consumer
  template:
    metadata:
      labels:
        app: quote-consumer
    spec:
      containers:
        - name: quote-consumer
          image: quay.io/jug-at-techgym/quote-consumer 
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600