kind: Service
apiVersion: v1
metadata:
  name: quote-consumer
  labels:
    app: quote-consumer
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: quote-consumer