apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: jug-demo-application
  labels:
    app: jug-demo-application
    app.openshift.io/runtime: quarkus
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jug-demo-application:latest
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile.native
  source:
    type: Git
    git:
      uri: 'https://github.ibm.com/jug-techgym-session-1/jug-demo-application.git'
    sourceSecret:
      name: git-credentials