apiVersion: apps/v1
kind: Deployment
metadata:
  name: jug-demo-application
  annotations:
     app.openshift.io/vcs-uri: "https://github.ibm.com/jug-techgym-session-1/jug-demo-application.git"
     image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"jug-demo-application:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"jug-demo-application\")].image"}]
  labels:
    app.openshift.io/runtime: quarkus
    app: jug-demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jug-demo-application
  template:
    metadata:
      labels:
        app.openshift.io/runtime: quarkus
        app: jug-demo-application
    spec:
      containers:
        - name: jug-demo-application
          image: image-registry.openshift-image-registry.svc:5000/btm-sogei/jug-demo-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10